### ISSUE TITLE
convobot create_driver error

### ISSUE THREAD

**Issue by hor1k1t4** [thomas-xin/Miza#26]
Hello again )

  result = self.fn(*self.args, **self.kwargs)                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                           
File "C:\Users\User\Desktop\Miza\misc\convobot.py", line 103, in create_driver                              
if "Current browser version is " in ex.args[0]:                                                                                                                                                                            IndexError: tuple index out of range

**Comment by thomas-xin** [comment]
That is weird, the web driver errored without arguments in the exception
I can fix the index error but I'm not sure about the underlying issue

**Comment by hor1k1t4** [comment]
I find error 😅
Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 110
