### ISSUE TITLE
cannot import name 'AsyncChatGPT' from 'chatgpt_wrapper'

### ISSUE THREAD

**Issue by hor1k1t4** [thomas-xin/Miza#30]
chatgpt_wrapper - 0.8.4
An error appears in the console, although the bot still answers the question.
After `ask`.

**Comment by thomas-xin** [comment]
This is actually a setup left over for backwards compatibility with the external library. It is not required, and the traceback is left over for debugging purposes. I will remove the default one for when it's not found at all though.
