### ISSUE TITLE
Why does bot have event to unmute and undeaf itself?

### ISSUE THREAD

**Issue by Duckrinium** [thomas-xin/Miza#31]
I am fine with unmute, to prevent people complaining about bot not playing music, but what's up with undeafen? Deafen is not preventing bot to play music, so why?

**Comment by thomas-xin** [comment]
This was actually quite an old feature, and the original intent was to allow the bot to play in AFK channels. Miza does not actually do anything with audio received, so for now deafen has no effect.

I *do* plan to implement a conversational agent in voice eventually, once I get one working reasonably well though.

**Comment by thomas-xin** [comment]
(At that point I will probably remove the auto unmute and undeafen, and it'd be an opt-in feature)

**Comment by Duckrinium** [comment]
I see! Thanks for explanation! :slightly_smiling_face: :heart:
