### ISSUE TITLE
Uncommented code

### ISSUE THREAD

**Issue by Galactipod** [thomas-xin/Miza#7]
None of the code I've looked at here was commented. You might understand your code, but other contributors might not. In fact, in a few months, you might come back to your code and not understand it anymore yourself.

**Comment by GDB-spur** [comment]
Can you be more specific? What files were you looking at?

**Comment by Galactipod** [comment]
I've looked at more files. Server.py seems to be the only one lacking commenting that's longer than a few lines. However, while the other files have comments, it can be considered sparse. IMO, there should be a comment every few lines rather than one for every "section" of code that can be several lines.

**Comment by ghost** [comment]
Hello, thank you for your feedback! The owner of the repo has put it into consideration and added comments to the server.py file. As for your other suggestion, while I understand where you're coming from, the owner did their best to state what things do with a code project as large as this. Not saying that your suggestion is to be ignored, but its not quite as important of a change to make at this current stage, also considering having the time. But thank you for taking the time to make a suggestion towards improvement. :)

**Comment by thomas-xin** [comment]
👌
